version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-networks

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-networks
    depends_on:
      - backend

networks:
  app-networks:
    driver: bridge